# fly.toml app configuration file generated for 17lands-helper-crimson-mountain-7385-falling-shape-5832-wild-rain-2690 on 2024-02-06T10:29:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '17lands-helper-crimson-mountain-7385-falling-shape-5832-wild-rain-2690'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
